# Generated by Django 4.2 on 2023-06-12 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_departamento_funcionario_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
